### ISSUE TITLE
Compilation fails on a recent Debian Stretch

### ISSUE THREAD

**Issue by leprovokateur** [gununu/xf86-video-sis-stable#3]
Hi,

I compile on a recent Debian Stretch: Following the instructions, "make" fails:

sis_driver.c: In function 'SISBlockHandler':
sis_driver.c:8796:6: error: too many arguments to function 'pScreen->BlockHandler'
     (*pScreen->BlockHandler) (BLOCKHANDLER_ARGS);
     ~^~~~~~~~~~~~~~~~~~~~~~~
sis_driver.c:8797:27: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     pScreen->BlockHandler = SISBlockHandler;
                           ^
sis_driver.c: In function 'SISScreenInit':
sis_driver.c:9929:27: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     pScreen->BlockHandler = SISBlockHandler;
                           ^
Makefile:531: recipe for target 'sis_driver.lo' failed
make[2]: *** [sis_driver.lo] Error 1
make[2]: Leaving directory '/home/user/xf86-video-sis-2017-07-23/xf86-video-sis-stable/src'
Makefile:444: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/xf86-video-sis-2017-07-23/xf86-video-sis-stable'
Makefile:376: recipe for target 'all' failed
make: *** [all] Error 2

I wasn't able to find a solution for this.

**Comment by gununu** [comment]
Thank you for your report.
The problem should have be fixed by a patch [0056a79](https://github.com/gununu/xf86-video-sis-stable/commit/0056a79a9d4811924ce726ce2ceecf358ada624e).
However I didn't actually confirm that this problem was fixed yet.

**Comment by leprovokateur** [comment]
Compilation succeeds now, thanks.

Sadly, I get a black screen after starting X. Should I open a new issue for this?

**Comment by gununu** [comment]
Feel free to open a new issue.
But I don't have motivation and time to fix this driver except compilation errors...
